#!/bin/bash

screen -r -S painel -X quit
cd /root/Painel-DTunnel
[[ -e /root/Painel-DTunnel/prime ]] && {
  screen -dmS "painel" sh start.sh
  echo
  echo "Painel-DTunnel Online (WAPI)"
  echo
  exit 0
}
touch prime
#echo "ps x | grep 'wapi' | grep -v 'grep' || cd /root/apiWa && sudo screen -dmS 'wapi' sh start.sh && cd /root" >> /etc/autostart
(crontab -l > /tmp/apiWaRes; echo "@reboot sleep 10 && pon" >> /tmp/apiWaRes; cat /tmp/apiWaRes) | crontab -
screen -dmS "painel" sh start.sh
echo
echo "Painel-DTunnel Online (PRIME)"
echo